---

postgres_apt_prerequisite_packages:
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https
postgres_apt_repo: https://apt.postgresql.org/pub/repos/apt/
postgres_apt_repo_gpg: https://www.postgresql.org/media/keys/ACCC4CF8.asc
