---

caddy_apt_prerequisite_packages:
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https
caddy_apt_repo: https://dl.cloudsmith.io/public/caddy/stable/deb/debian
caddy_apt_repo_gpg: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
